Add homepage and all necessary linters files
jrosario19/Juan-Rosario-Portfolio pull request #1
Opened 2022-03-16 22:57 UTC by jrosario19

## Added the home page in mobile version:
- Navbar.
- Headline section

### I also include the files needed in the project.
- Index.html file, Include the Nav 
- style.css file
- All necessary linters files.

2022-03-16 23:15 UTC, keroloussamy requested changes
Hi @jrosario19, 

Good job so far! You really did a great work
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

## Required Changes ♻️
_Check the comments under the review._

![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-16 23:15 UTC, keroloussamy commented on index.html
> +                <li class="logo"> <h3>Welcome</h3></li>
- [ ] Kindly wrap your `<h3>Welcome</h3>` inside an `a` tag, to make it link to your home page, every logo should link to the home page.

2022-03-16 23:15 UTC, keroloussamy commented on styles.css
> +}
- [ ] Kindly remove the `margin: 0 24px;` role, to match the figma design.

![image](https://user-images.githubusercontent.com/35535130/158706130-121f1b75-641c-4ebe-97a5-ac1a2f28e69e.png)

2022-03-16 23:15 UTC, keroloussamy commented on index.html
> +            </ul>
- [ ] Kindly add this button at the end of your headline section, to match the Figma design.

This one
![image](https://user-images.githubusercontent.com/35535130/158706438-d93fbcba-9a5b-41b3-b994-ec14f646c112.png)

2022-03-17 00:20 UTC, smunozmo approved these changes
Hi @jrosario19 , 👋 

Your project is complete!  There is nothing else to say other than... it's time to merge it! 🚀 
Very nice work, congratulations! 🎉 

<img src="https://media4.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>

Cheers and Happy coding! 🤓 

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-17 00:20 UTC, smunozmo commented on index.html
> +                <li class="logo"> <a href="index.html"><h3>Welcome</h3></a></li>
- Good work using an `a` tag on your logo.

2022-03-17 00:20 UTC, smunozmo commented on styles.css
> +}
- The margin was removed, well done!

2022-03-17 00:20 UTC, smunozmo commented on index.html
> +            <a href="#"><img src="images/Disabled.svg" alt=""></a>
- You added the missing button, great job.

2022-03-17 00:24 UTC, merged